// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICr4Zsf0R1gGxN0lOtiYIcvAsquUUQv0',
    appId: '1:978010372188:web:9512b37a993aed4c288e99',
    messagingSenderId: '978010372188',
    projectId: 'codifyqq',
    authDomain: 'codifyqq.firebaseapp.com',
    storageBucket: 'codifyqq.firebasestorage.app',
    measurementId: 'G-323SLBHT0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-LYDtaOBQvf7vxvifDBywjVs4hTkikE',
    appId: '1:978010372188:android:e1b70f16b99871a9288e99',
    messagingSenderId: '978010372188',
    projectId: 'codifyqq',
    storageBucket: 'codifyqq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmIA3okwHmg7zzulS0P3z4GFF9W1OZDrQ',
    appId: '1:978010372188:ios:c8414faaa5300d20288e99',
    messagingSenderId: '978010372188',
    projectId: 'codifyqq',
    storageBucket: 'codifyqq.firebasestorage.app',
    androidClientId: '978010372188-8vj6olfm05dqhj1pu4jrp2e5eke3octu.apps.googleusercontent.com',
    iosClientId: '978010372188-7ihoh0sl9mgp255vnr8suhv8eq5u6sm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.codify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmIA3okwHmg7zzulS0P3z4GFF9W1OZDrQ',
    appId: '1:978010372188:ios:c8414faaa5300d20288e99',
    messagingSenderId: '978010372188',
    projectId: 'codifyqq',
    storageBucket: 'codifyqq.firebasestorage.app',
    androidClientId: '978010372188-8vj6olfm05dqhj1pu4jrp2e5eke3octu.apps.googleusercontent.com',
    iosClientId: '978010372188-7ihoh0sl9mgp255vnr8suhv8eq5u6sm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.codify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCICr4Zsf0R1gGxN0lOtiYIcvAsquUUQv0',
    appId: '1:978010372188:web:30cbe15d7815f938288e99',
    messagingSenderId: '978010372188',
    projectId: 'codifyqq',
    authDomain: 'codifyqq.firebaseapp.com',
    storageBucket: 'codifyqq.firebasestorage.app',
    measurementId: 'G-JGHSWCXCCQ',
  );
}
